### PR TITLE
Replace getitemlink with getitemname in menu

### PR DESCRIPTION
**Pull request by wushin**

### CODE REVIEW

**Comment by wushin** [comment]
@nashley thats why the @@s

**Comment by wushin** [comment]
@mekolat mer.

**Comment by mekolat** [comment]
@wushin don't you dare merge this. Just make her say "did you bring me some getitemlink(...) ?" and then in the menu put yes, no, I have a letter for you

**Comment by wushin** [comment]
@mekolat what do we do about ./world/map/npc/012-1/injured-mouboo.txt's menu

**Pull request merged**
