### PR TITLE
update game rules

### PR DESCRIPTION
**Pull request by Helianthella**

### CODE REVIEW

**Comment by wushin** [comment]
So far this is looking more like what it is going to be.

Keyloggers, hoaxes/phishing websites
Hateful language about race, religion, country (Example: US vs. EU), political beliefs, gender, etc.
Nudity/Sexually explicit content
Content that is considered illegal by law
Referral links for contests, promotions, or anything else
Medical advice

**Comment by wushin** [comment]
@mekolat Official list is in https://www.themanaworld.org/index.php/Game_Rules

**Comment by mekolat** [comment]
@wushin is this good to merge?

**Comment by mekolat** [comment]
@wushin I made this PR edit-able so you can change it to your liking

**Pull request closed without merging**
