### PR TITLE
Heathin's terra arrows bug

### PR DESCRIPTION
**Pull request by RelaxMore**
Heathin told me: "You are lucky, I could forge 0 more arrows than expected."
I've tried to correct the bug but not sure whether my sntax of 'if' is correct.

### CODE REVIEW

**Comment by wushin** [comment]
Syntax would be 
mes "\"Here you go!";
if (@lucky > 0)
    mes "lucky statement";
mes "comeback statement";

the statements being the relevant parts of the npc text

**Comment by RelaxMore** [comment]
But wouldn't that make the message get devided by new lines into 3 lines? Like mes "[Heathin]"; gives a single line to "[Heathin]".

**Comment by nashley** [comment]
@RelaxMore It would only result in two lines, but to avoid even that, you can do something like this:
```
    if(@lucky>0)
        goto L_Lucky;
    mes "\"Here you go! comeback statement\"";

L_Lucky:
    mes "\"Here you go! lucky statement\"";
```

**Comment by mekolat** [comment]
There's also another solution:
```
if(@lucky>0)
set @lucky$, " You are lucky, I could forge "+@lucky+" more arrows than expected.";
mes "Here you go!" + @lucky$ + " Come back again if you want more Terranite Arrows.\"";
```

**Comment by RelaxMore** [comment]
Please make the change. I just don't understand that when:

`mes "[Heathin]";`
means
`cout << "[Heathin]\n";`

(Note the `\n`s)

then why wouldn't

`mes "\"Here you go!";`
`if (@lucky > 0)`
`mes "lucky statement";`
`mes "comeback statement\"";`
mean
`cout<<"\"Here you go!\n";`
`if ($lucky > 0)`
`cout<<"lucky statement\n";`
`cout<<"comeback statement\"\n";`

which gives output:
> "Here you go!
> lucky statement
> comeback statement"

I haven't understoond this language. Please make the change.

**Comment by nashley** [comment]
@RelaxMore 
The `if` follows exactly one line due to the lack of brackets (both in this script and the language itself), so it basically says this:
```
printf("Here you go!");
if(luck>0){
// Only print this if luck > 0
printf("lucky statement");
}
// Print this either way
printf("comeback statement");
```
I miscounted lines in an earlier reply, and that may have messed you up; sorry if it did.

**Comment by mekolat** [comment]
@RelaxMore https://github.com/themanaworld/tmwa-server-data/pull/356

**Comment by RelaxMore** [comment]
I know that if follows only 1 line without braces (brakets here).

I was trying to do:
```
cout<<"\"Here you go!";
if (lucky > 0)
 cout<<" You are lucky, I could forge " <<lucky <<" more arrows than expected.";
cout<<" Come back again if you want more Terranite Arrows.\"";
```
which gives ouput: (assuming luck=10)
> "Here you go! You are lucky, I could forge 10 more arrows than expected. Come back again if you want more Terranite Arrows."

But Wushin's method seems to me to be giving output: (dividing a single line into 3 lines)
> "Here you go!
>  You are lucky, I could forge 10 more arrows than expected.
>  Come back again if you want more Terranite Arrows."

I am assuming that `mes` adds a new line '\n' at the end. I'm assuming this because:
````
mes "[Heathin]";
mes "\"Here you go! You are lucky, I could forge "+@lucky+" more arrows than expected. Come back again if you want more Terranite Arrows.\"";
```
was giving output:
> [Heathin]
> "Here you.. "

Notice that "Here you.. " starts in a new line.

**Comment by nashley** [comment]
@RelaxMore, @mekolat had the best solution to getting it all on one line:
```
if(@lucky>0)
set @lucky$, " You are lucky, I could forge "+@lucky+" more arrows than expected.";
mes "Here you go!" + @lucky$ + " Come back again if you want more Terranite Arrows.\"";
set @lucky$, "";
```

**Pull request closed without merging**
