### PR TITLE
fix sorfina zeny

### PR DESCRIPTION
**Pull request by mekolat**

### CODE REVIEW

**Comment by wushin** [comment]
Did I reduce how much they gave?

**Comment by mekolat** [comment]
@wushin when the player did the tutorial they only got 30 zeny but when skipping it they got 50 so I put both 50

**Comment by wushin** [comment]
I believe that's because she gives tanisha's money when you skip.

**Comment by mekolat** [comment]
tanisha gives money?

**Comment by wushin** [comment]
Well technically they should both end up with 35 30 from sorfina and 5 from tanisha.
Either leave this and make tanisha hand out 20 or change the 50 to 35

**Pull request merged**
