### PR TITLE
Don't remove towels from inventory on usage

### PR DESCRIPTION
**Pull request by rumly111**
Due to https://forums.themanaworld.org/viewtopic.php?f=4&t=19395.

This fix prevents removing multiple towels from player's inventory, when you use one. You won't lose towels accidently anymore.

### CODE REVIEW

**Comment by wushin** [comment]
Don't just comment it out. remove the function at the bottom and delete the functionality.

**Comment by rumly111** [comment]
fixed

**Comment by wushin** [comment]
@rumly111 Wanna decrease the cooldown to 20 minutes and we can merge this in next release?

**Comment by rumly111** [comment]
@wushin done

**Comment by wushin** [comment]
@rumly111 Danke

**Pull request merged**
