### PR TITLE
Fix weelos if statement

### PR DESCRIPTION
**Pull request by wushin**
Switch charset of letter in NPC name

### CODE REVIEW

**Comment by mekolat** [comment]
why did you remove the ç ? it was not a typo, it was intended like that

**Comment by wushin** [comment]
I know you intended it like that but it's breaking Evol-Hercules conversion and a few scripts associated with that.

**Comment by o11c** [comment]
If there are scripts broken by utf-8, fix those scripts.

I see absolutely no reason to avoid utf-8 in script strings of any sort.

**Comment by wushin** [comment]
Nah, its not just scripts, the non-English people think this is weird plus it's causing all sorts of weird problems with people trying to deal with stuff. So no. It's out. English only in scripts. You want to use Gracon, fine but no mixing char sets in text or names. It confuses the hell out of people translating. Since this NPC has been in like 8 different times It got reported as a bug. So no.

**Comment by wushin** [comment]
ok, I'd rather fix weelos to the script standard than worry about that char. reverted the ç.

**Pull request merged**
