### PR TITLE
add ghost town

### PR DESCRIPTION
**Pull request by mekolat**
This PR turns Hurnscald into a ghost town when there is less than 10 players in town.
Inspired by Silent Dawn's idea

### CODE REVIEW

**Comment by wushin** [comment]
Hrmm... I like the idea, but Hurnscald... Hrmm...

**Comment by mekolat** [comment]
It works well

**Comment by mekolat** [comment]
@wushin I close this since you intend to do this in the undead town

**Comment by Cassy1** [comment]
O.o seriously? I freaking love this idea! Just saying.

**Comment by wushin** [comment]
@Cassy1 my thought was to use it with the underworld map i made

**Comment by Cassy1** [comment]
@wushin that would totally make sense. I just doubt there will be enough users there. We will see.

**Pull request closed without merging**
