### PR TITLE
Remove Unequip from a map

### PR DESCRIPTION
**Pull request by wushin**

### CODE REVIEW

**Comment by wushin** [comment]
@mekolat So we missed making this change after the -1 to 32767. Now that this works however we have some interesting script cases that can happen.

**Comment by mekolat** [comment]
@wushin interesting cases?

**Comment by wushin** [comment]
@mekolat magic to script needed this to work.

**Comment by mekolat** [comment]
I'm still wondering why this requires a timer instead of being directly unequipped

**Comment by wushin** [comment]
there was a bug at one time, I forget what it was or if it still exists.

**Comment by wushin** [comment]
I think it had to do if you had multiple pieces of gear that had checks.

**Pull request merged**
