### PR TITLE
Initial Conversion TMW -> Herc

### PR DESCRIPTION
**Pull request by wushin**

### CODE REVIEW

**Comment by Bertram25** [comment]
Congrats. :)

**Comment by mekolat** [comment]
can't wait, my body is ready

**Comment by wushin** [comment]
If this goes live the next step is to back off all the converted data from the "confs".
There are only a few things that need to be fixed yet for the converter. 
Both servers can run in the same converted repo but tmwa-monitor will break. 
This PR is merely for working test purposes.

**Comment by Bertram25** [comment]
> This PR is merely for working test purposes.

I don't care, this is epic. ;)

**Pull request closed without merging**
