### PR TITLE
make the sanguine vault a pvpon area

### PR DESCRIPTION
**Pull request by mekolat**
requires https://github.com/themanaworld/tmwa-client-data/pull/233

### CODE REVIEW

**Comment by wushin** [comment]
@mekolat Can you look to see how Pvp is handled in Hercules/Evol?

**Comment by mekolat** [comment]
@wushin this will have to wait because I'm not mentally able to code at the moment (influenza).. just looking at the screen makes me dizzy

**Comment by wushin** [comment]
@mekolat no worries buddy. Get well, maybe by the time your done being sick I'll have evol-herc running. just about got the converter going good for it.

**Comment by mekolat** [comment]
This PR also adds TinyManaElixir, SmallManaElixir, MediumManaElixir and LargeManaElixir to the potion shop, at 4 times the original price. If it is still too high, I will drop the price to 3 times in a future PR.

**Comment by mekolat** [comment]
@wushin rebased after https://github.com/themanaworld/tmwa-server-data/issues/287 and ran "make maps" with the updated rasterizer

**Comment by wushin** [comment]
@mekolat table this for now?

**Comment by mekolat** [comment]
@wushin why? It's working

**Pull request closed without merging**
