### PR TITLE
update submodule tools

### PR DESCRIPTION
**Pull request by mekolat**

### CODE REVIEW

**Comment by wushin** [comment]
What did we miss here or is this for something else?

**Comment by mekolat** [comment]
@wushin it's because we removed the old emotes from client-data so it was causing the update script to barf on update-emotes.zip so I removed emotes from the update script and now it needs a submodule commit

**Comment by wushin** [comment]
@mekolat Ahh ok.

**Comment by wushin** [comment]
@mekolat we don't merge these via git because git gets weird about them.

**Pull request closed without merging**
