### PR TITLE
first steps towards auto-generated npcs

### PR DESCRIPTION
**Pull request by mekolat**
done:
- keep only one mapless npc (global handler)

to-do:
- convert npcs to functions, group them by modules
- since functions can not have timers, detach all timers and put them in npc/timers. call them with `initnpctimer NPC;`

### CODE REVIEW

**Comment by wushin** [comment]
Has a conflict with another PR

**Comment by wushin** [comment]
@guessing -1 to 32657

**Comment by mekolat** [comment]
@wushin don't put this in milestone, it's gonna take a while

**Comment by wushin** [comment]
@mekolat can't we do it in steps?

**Comment by mekolat** [comment]
@wushin we can do everything but I want to modify every single npc to make them a function and this is gonna take a while

**Comment by wushin** [comment]
@mekolat We will do 1 map at a time.I'll make make maps work both ways.

**Comment by mekolat** [comment]
@wushin ok then this pr will be to create the basic folder structure and convert a few npcs if I have time

**Comment by wushin** [comment]
@mekolat ok, but I was working on 029-1 and 029-2. We can do this one as well.

**Comment by wushin** [comment]
@mekolat merge conflict

**Pull request closed without merging**
