### PR TITLE
Add Beret

### PR DESCRIPTION
**Pull request by RelaxMore**

### CODE REVIEW

**Comment by mekolat** [comment]
no

**Comment by nashley** [comment]
Are there even graphics for this?

**Comment by RelaxMore** [comment]
meko, I've already sold mine. a player requested me to add.
nashley, yes there are, you can see with /createitems

**Comment by wushin** [comment]
@RelaxMore the beret isn't supposed to be in game yet. Currently you have to edit each variant by color into both the client and server data. Feel free to check anything that is dyed currently. 

Hopefully soon we will have a better system for colors of items.

**Comment by nashley** [comment]
What would a better dye system look like? Just replacing the array or
making an item dyeable without manual editing?

**Comment by wushin** [comment]
@nashley To store the variation as part of the item.

**Comment by mekolat** [comment]
@wushin `Currently you have to edit each variant by color into both the client and server data. Feel free to check anything that is dyed currently.`
<hr/>
hm what do you mean? all the berets already follow the color convention so just adding them to the array would work.

**Pull request closed without merging**
