### PR TITLE
Terranite Cave Ownership

### PR DESCRIPTION
**Pull request by wushin**

### CODE REVIEW

**Comment by mekolat** [comment]
I'd rather make the monoliths into puppets controlled by a single `#TCOConfig` "puppeteer" so that those nodes can easily be spawned, destroyed, moved at will

**Comment by wushin** [comment]
@mekolat Except that codes not merged yet.

**Comment by wushin** [comment]
@mekolat time to revisit

**Comment by mekolat** [comment]
not adding new content

**Pull request closed without merging**
